version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    environment:
      CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: yarn deploy
