version: 2.1
jobs:
  Publish-to-Pages:
    docker:
      - image: cimg/node:18.7.0

    steps:
      - checkout
      # Run your project's build step
      - run: npm install
      # Publish with wrangler
      - run: yarn deploy

workflows:
  Publish-to-Pages-workflow:
    jobs:
      - Publish-to-Pages
